load_generator:
  debug: True
  duration: 30                # number of seconds for the run
  wait_periods:
    - wait: 0.1           # in seconds
      duration: 5
    - wait: 5           # in seconds
      duration: 10

funk_generator:
  decompress:
    filename: 'dfaastest/synthetic_functions/decompress.py'
    zipfilename: 'dfaastest/synthetic_functions/decompress.zip'
    handler_name: 'dfaastest.synthetic_functions.decompress.lambda_handler'
    role_name: 'LogProcessorRole'
    function_name: 'dfaastest_decompress'
    description: 'Compress text into a file and decompress'
    runtime: 'python3.9'
    api_name: 'dfaastest-decompress-rest-api'
    api_base_path: 'mcs598-dfaastest-decompress'
    api_stage: 'test'
    params: []
    module: 'synthetic_functions.decompress'
  factorial_1:
    function_name: 'CpuIntensiveFunction'
    api_name: 'CpuIntensiveFunction-API'
    api_base_path: 'CpuIntensiveFunction'
    api_stage: 'default'
    params: []
    module: 'synthetic_functions.cpu_intensive'
  array_summation_1:
    function_name: 'MemoryIntensiveFunction'
    api_name: 'MemoryIntensiveFunction-API'
    api_base_path: 'MemoryIntensiveFunction'
    api_stage: 'default'
    params: []
    module: 'synthetic_functions.mem_intensive'
  grayscale_conversion_1:
    function_name: 'ImageProcessingFunction'
    api_name: 'ImageProcessingFunction-API'
    api_base_path: 'ImageProcessingFunction'
    api_stage: 'default'
    params: [ ]
    module: 'synthetic_functions.image_processing'


database:
  host: ''
  user: ''
  pass: ''
  db_name: ''
  table: ''

cmab_agent:
  function_name: 'cmab-agent'
  api_name: 'cmab-agent-rest-api'
  api_base_path: 'cmab-agent'
  api_stage: 'test'
  model_funk:  # passed in at runtime from the operator
  model_experiment:  # passed in at runtime from the operator

operator:
  wait_period: 30 # seconds
  recommend_payload_algorithm: 'wait_period' # 'wait_period', 'last_10', 'last_100'
